# Generated by Django 3.1.5 on 2021-06-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_order_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripton',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
